### ISSUE TITLE
Switch for charger_max_ampere

### ISSUE THREAD

**Issue by loeffelpan** [lendy007/homeassistant-skodaconnect#11]
I would like to change the ability to adjust `charger_max_ampere` for an automation with my solar battery.

Is this possible?

**Comment by Farfar** [comment]
At the moment no. But could be implemented.
Is this for a PHEV or BEV?
Because I would need more data from BEVs, what values the car reports, what the API returns etc.
My Superb iV returns 254 as value for maximum current (16 A) and 252 for reduced (5-6 amps). For BEVs I would need to now all values and corresponding values in car/app.

**Comment by loeffelpan** [comment]
I have a Superb iV, too.
Would be nice to trigger the car to start charging either with maximum or reduced current, depending on available power from solar system.

**Comment by Farfar** [comment]
.

> I have a Superb iV, too.
> Would be nice to trigger the car to start charging either with maximum or reduced current, depending on available power from solar system.

This will probably be best to do via a service call. For Superb iV it's only two values but other models might have more levels to set. Easiest is to plan for both directly.

I don't think you can send a start charging request at the same time as a request to change charging current, they will consume two requests.

**Comment by loeffelpan** [comment]
I‘m new to homeassistant, so... no idea. But I will try if you implement this. Sound not to be complicated.

> Easiest is to plan for both directly.
Unfortunatly I don‘t anybody with an BEV to get the other values. Can you implement this for PHEV with two values first? Maybe in another branch. So I can continue with my automation?

**Comment by loeffelpan** [comment]
Can you explain how you imagine to automate this?
I'm not sure how to use this with service calls or how to create a sequence of two actions.

**Comment by Farfar** [comment]
> Can you explain how you imagine to automate this?
> I'm not sure how to use this with service calls or how to create a sequence of two actions.

Do you know how to use service calls?
If not you can read more here: https://www.home-assistant.io/docs/scripts/service-calls

Imagine there's a service call named 'skodaconnect.set_charger_ampere' that takes two data parameters, 'vin' and 'ampere'.
Then you would call it with:
```
service: skodaconnect.set_charger_ampere
data:
  vin: vwsj123as123152
  ampere: <value>
```
Where vin is the vin number of your car and ampere is either a numeric value or one of "reduced" or "maximum", I haven't decided since I don't know yet how BEV's handle the configuration value.

**Comment by loeffelpan** [comment]
Ah. I got it.
The service have to be implemented by the integration (by you) and my automation can call it. Sounds good. The same thing would work for setting charging plans and things like that. Maybe you could implement this, too (not urgent but in future).

To be most compatible, I would devide it into two services. `skodaconnect.set_charger_ampere_phev` and `skodaconnect.set_charger_ampere_bev`.
So, nobody has to change their automations if you implement that feature for BEV.

Do you need to provice the VIN in that service call? The integration is globally configured for a specific VIN. I don‘t see a need for this.

**Comment by Farfar** [comment]
> Maybe you could implement this, too (not urgent but in future).
It's planned for the future but it's not easy to implement in a good way.



> So, nobody has to change their automations if you implement that feature for BEV.
When implemented it will be one service.



> Do you need to provice the VIN in that service call? The integration is globally configured for a specific VIN. I don‘t see a need for this.
Yes the way the library and integration is written right now the vin is needed. The service call is global but there might be more than one vehicle for the account. Also since there's a library talking to the backend the vin is needed to get the correct class object to make the API calls.

**Comment by loeffelpan** [comment]
I see. Thanks for explaination.
Any idea when this will be implemented?
I need that to go on with my automation.

**Comment by Farfar** [comment]
> I see. Thanks for explaination.
> Any idea when this will be implemented?
> I need that to go on with my automation.

When I have the time for it. Everything between tomorrow and within the week.

**Comment by Farfar** [comment]
> I see. Thanks for explaination.
> Any idea when this will be implemented?
> I need that to go on with my automation.

New release v1.0.32 available with said function.
