### ISSUE TITLE
Get switch for reduce power

### ISSUE THREAD

**Issue by hofvanta** [lendy007/homeassistant-skodaconnect#144]
For charging is nice to have a switch (instead of sensor) to reduce power and also that the status is updated to the current state.

**Comment by ChristophCaina** [comment]
I agree, since you do have such an option within the App for the Enyaq - it would be nice to have it in the Integration as well (even, if I never really used this option)

**Comment by hofvanta** [comment]
Sometimes I need to charge at locations without 7-11kW charging points but only 3,6-5kW. Also sometimes I want to delay charging when parked to not get a fine, when I at the other side of the city and not able to return on time. Now I need to call a service and the state not always updated well.

**Comment by Farfar** [comment]
> Sometimes I need to charge at locations without 7-11kW charging points but only 3,6-5kW. Also sometimes I want to delay charging when parked to not get a fine, when I at the other side of the city and not able to return on time. Now I need to call a service and the state not always updated well.

For cars other than Enyaq we can set charging current to values other than reduced/max (1-16 for my Superb for instance).
I won't, at least not at the moment, implement any further logic for such a button since it's easily done via Home Assistant built-in functions.



> Sometimes I need to charge at locations without 7-11kW charging points but only 3,6-5kW. Also sometimes I want to delay charging when parked to not get a fine, when I at the other side of the city and not able to return on time. Now I need to call a service and the state not always updated well.

If the state isn't updated well it won't help you with a dedicated button vs the sensor since the information is polled from the same place.
If it takes time before the status is updated you can try to reduce the polling interval in the integration settings.
