### ISSUE TITLE
Departure timers vs charger current

### ISSUE THREAD

**Issue by loeffelpan** [lendy007/homeassistant-skodaconnect#89]
In your description of `service.set_charger_max_current` there is to read:
`Set the maximum current used for charger. Overrides the current setting in departure timers.`
How does this really affect each other?
Should setting a departure timer set the current to the chosen value?
Or does it affect the timers only when setting any current *after* setting the timer?

Maybe you could help me understand this.

**Comment by Farfar** [comment]
They are linked in the sense that the service "service.set_charger_max_current" modifies the global setting of maximum charging current while the "service.set_departure_schedule" modifies the maximum charging current for that particular departure plan.
IIRC the global setting overrides the plans so it the global setting is reduced/6A then the plans won't be able to charge with higher current than that even if they are set.tp a higher value.
But it's been a while since I tested this.
