### ISSUE TITLE
Lock control Enyaq

### ISSUE THREAD

**Issue by vBrolin** [lendy007/homeassistant-skodaconnect#94]
![66F20397-1801-4519-B85A-CBAA500F4C0D](https://user-images.githubusercontent.com/59017507/144919122-5c165b66-160d-41ff-9dd8-54d0981914d9.jpeg)
According to the picture from Play store and the app change log, it seems to be possible to control the lock of MY22 Enyaqs now.
Have not been able to verify since I don't have a Android device to test on.

**Comment by bslefevre** [comment]
So I've checked on my Android Tablet and version 1.5 from the playstore doesn't seem to have those options
![image](https://user-images.githubusercontent.com/5653833/144990474-da4d39e1-14a1-4062-aec3-f086ed74e763.jpeg)

**Comment by vBrolin** [comment]
Not available yet, excepted early next year according to Skoda

**Comment by Farfar** [comment]
> Not available yet, expected early next year according to Skoda

Is it available yet?

**Comment by JanDetrez** [comment]
Nope

**Comment by Farfar** [comment]
I have read in a response from Skoda support that only new Enyaq IV's, manufactured from january 2022, will get the remote lock/unlock function.
We'll see if it will work for older Enyaq as well since Skoda support isn't really known to be right all the time.  But until there's new Enyaq iV's with the ability to lock/unlock in app I won't be able to reverse engineer the function. So this issue will remain closed.
